# Generated by Django 5.0.3 on 2024-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_alter_consulta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(choices=[('oito', '08:00'), ('09:00', '09:00'), ('dez', '10:00'), ('onze', '11:00'), ('duas', '14:00'), ('tres', '15:00'), ('quatro', '16:00'), ('cinco', '17:00')], max_length=50, null=True),
        ),
    ]
